url: https://download.pitchblackwallpaper.tecdrop.com

title: Pitch Black Wallpaper

theme: false

repository: tecdrop/DownloadAPitchBlackWallpaper

collections:
  wallpapers:
    output: true

defaults:
  - scope:
      path: ""
      type: "wallpapers"
    values:
      layout: wallpaper

